name: todomobx
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
flutter:
  uses-material-design: true

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/todo_icon.png"
